# --- !Ups

INSERT INTO city(name) VALUES('Sarajevo');
INSERT INTO city(name) VALUES('Mostar');
INSERT INTO city(name) VALUES('Zenica');
INSERT INTO city(name) VALUES('Tuzla');

INSERT INTO "user"(name, address, city_id, email, hash, salt, phone, is_admin) SELECT 'Admin User', 'Address 1', city.id, 'admin@email.com', 'JUZcMpgHSG8kD4Jczpi/1roRe1aD3sndpU2BqEpZLmc=', 'RMiZBLS/BW1qEGGG1cwRrg==', '+387-061/904-989', true FROM city WHERE name = 'Sarajevo';
INSERT INTO "user"(name, address, city_id, email, hash, salt, phone, is_admin) SELECT 'Regular User', 'Address 2', city.id, 'test@email.com', 'Iqnhz5rU+5cGkx+CjtjjIZD9pnrstLljOxRPvzzFk3A=', '+lE0ZIG4cXq/0z4PmEiTxQ==', '+38761123456', NULL FROM city WHERE name = 'Sarajevo';

INSERT INTO cuisine(name) VALUES ('American');
INSERT INTO cuisine(name) VALUES ('Chinese');
INSERT INTO cuisine(name) VALUES ('Continental');
INSERT INTO cuisine(name) VALUES ('Cuban');
INSERT INTO cuisine(name) VALUES ('French');
INSERT INTO cuisine(name) VALUES ('Greek');
INSERT INTO cuisine(name) VALUES ('Indian');
INSERT INTO cuisine(name) VALUES ('Indonesian');
INSERT INTO cuisine(name) VALUES ('Italian');
INSERT INTO cuisine(name) VALUES ('Japanese');
INSERT INTO cuisine(name) VALUES ('Korean');
INSERT INTO cuisine(name) VALUES ('Lebanese');
INSERT INTO cuisine(name) VALUES ('Malaysian');
INSERT INTO cuisine(name) VALUES ('Mexican');
INSERT INTO cuisine(name) VALUES ('Pakistani');
INSERT INTO cuisine(name) VALUES ('Russian');
INSERT INTO cuisine(name) VALUES ('Singapore');
INSERT INTO cuisine(name) VALUES ('Spanish');
INSERT INTO cuisine(name) VALUES ('Thai');
INSERT INTO cuisine(name) VALUES ('Tibetan');
INSERT INTO cuisine(name) VALUES ('Vietnamese');
INSERT INTO cuisine(name) VALUES ('Persian');

INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Glass Exchange', city.id, '730 Constitution Ave.', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Bengal Way', city.id, '72 Elm Dr.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Caviar Junction', city.id, '8 Sherman Ave.', '+000-111/22-33-44', 4, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Cinnamon Room', city.id, '969 Windfall Lane', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Grand Hook', city.id, '19 Spruce Ave.', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Melting Pot', city.id, '9413 West Vale Dr.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Roadhouse', city.id, '93 W. Myrtle Drive', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Friends', city.id, '22 South Adams Dr.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Crickets', city.id, '759 Cross Ave.', '+000-111/22-33-44', 4, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Island', city.id, '980 Wood Ave.', '+000-111/22-33-44', 4, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Crimson Leaf', city.id, '880 Wild Horse Street', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Proud Cottage', city.id, '128 N. Glenholme Street', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Enigma Archive', city.id, '9 Mayfield St.', '+000-111/22-33-44', 4, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Fresh Merchant', city.id, '41 Delaware Street', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Modern Violin', city.id, '9029 North Ridgeview St.', '+000-111/22-33-44', 1, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Cellar', city.id, '62 Arrowhead St.', '+000-111/22-33-44', 1, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Curiosity', city.id, '58 Tailwater St.', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Mirage', city.id, '7080 Thompson St.', '+000-111/22-33-44', 1, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Smile', city.id, '9702 Inverness Road', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Polar Paradise', city.id, '194 Acacia Lane', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Noodle Saloon', city.id, '823 Wilson Street', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Vintage Archive', city.id, '589 Sierra St. East', '+000-111/22-33-44', 4, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Southern Dragon', city.id, '7058 Tower Court', '+000-111/22-33-44', 1, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Harlequin Lighthouse', city.id, '9957 Central Road', '+000-111/22-33-44', 2, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Little Persia', city.id, '24 Parker Rd.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'Brimstone', city.id, '57 W. Edgewater St.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';
INSERT INTO restaurant(name, city_id, address, phone, price_range, cover_image_path, profile_image_path, description, menu, latitude, longitude) SELECT 'The Emperor', city.id, '623 Rocky River Ave.', '+000-111/22-33-44', 3, 'https://abhrestaurants.s3.amazonaws.com/placeholder-cover.jpg', '/assets/images/rPlaceholder.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget purus ac massa vulputate mattis. Nullam luctus commodo placerat. Mauris imperdiet lorem dolor, pharetra molestie arcu commodo sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam hendrerit libero id elit tincidunt mollis. Cras at faucibus elit. Donec ut lectus ex. Nullam ac venenatis massa, et porta nisi. Praesent eu dignissim nulla. Fusce id bibendum tortor.', '{}', 0, 0 FROM city WHERE name = 'Sarajevo';

# --- !Downs

TRUNCATE restaurant, "user", city, cuisine, restaurant_cuisine, restaurant_table CASCADE;